from pathlib import Path


# ProjectManager/
PROJECT_ROOT = Path(__file__).resolve().parent

# ProjectManager/
#     ↓
# PERSONALES/
#     ↓
# PROYECTOS/
#     ↓
# PROGRAMACION/
PROGRAMACION_ROOT = PROJECT_ROOT.parent.parent.parent

TEMPLATES_DIR = PROGRAMACION_ROOT / "TEMPLATES"
PROJECTS_DIR = PROGRAMACION_ROOT / "PROYECTOS"
TOOLS_DIR = PROGRAMACION_ROOT / "TOOLS"
ENVIRONMENTS_DIR = PROGRAMACION_ROOT / "ENVIRONMENTS"
FEATURES_DIR = PROGRAMACION_ROOT / "FEATURES"
TECHNOLOGIES_DIR = PROGRAMACION_ROOT / "TECHNOLOGIES"